In [2]:
#Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:
import numpy as np
sa=np.random.randint(1000,5001,30)
sa


array([3234, 2430, 3501, 4737, 4099, 4811, 2130, 4244, 3446, 2455, 2863,
       3124, 4499, 2025, 1487, 4607, 4437, 3878, 1595, 2931, 3448, 1747,
       3357, 4111, 3849, 2644, 2400, 4463, 4354, 2482], dtype=int32)

In [2]:
sa.sum()

np.int64(95811)

In [3]:
sa.mean()

np.float64(3193.7)

In [4]:
np.sort(sa)[-5:]

array([4378, 4674, 4832, 4866, 4941], dtype=int32)

In [5]:
!git add .

In [10]:
!git commit -m "numpy practice"

[main c6dce43] numpy practice
 2 files changed, 85 insertions(+), 10 deletions(-)


In [11]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   d4769b3..c6dce43  main -> main


In [18]:
data = np.random.randint(10, 101, 100)


mean = np.mean(data)
std = np.std(data)


z_scores = (data - mean) / std


outliers = data[np.abs(z_scores) > 3]
outliers


array([], dtype=int32)

In [19]:
!git add .

In [20]:
!git commit -m "z score method"

[main 6152422] z score method
 1 file changed, 123 insertions(+), 11 deletions(-)


In [21]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   c6dce43..6152422  main -> main


In [27]:
#normalizing using min-max

a=np.array([120, 150, 200, 250, 300])
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
normalized

array([0.        , 0.16666667, 0.44444444, 0.72222222, 1.        ])

In [28]:
!git add .

In [29]:
!git commit -m "normalization"

[main 6c94de1] normalization
 1 file changed, 73 insertions(+), 18 deletions(-)


In [30]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   6152422..6c94de1  main -> main


In [31]:
age=np.array([18,22,25,30,35,40,45,50,55,60])
age.mean()

np.float64(38.0)

In [35]:
np.median(age)

np.float64(37.5)

In [39]:
age.std()

np.float64(13.66747965061591)

In [81]:
!git add .

In [82]:
!git commit -m "data manipulation"

[main 17db9a4] data manipulation
 1 file changed, 47 insertions(+), 11 deletions(-)


In [83]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   0492079..17db9a4  main -> main


In [19]:
su=np.random.randint(1,101,(10,5))
su

array([[24, 66, 32, 38, 18],
       [76,  8, 63, 74, 72],
       [55, 54,  6, 19, 30],
       [94, 45, 20, 31, 88],
       [34, 42, 13, 45, 94],
       [20, 23, 94, 14, 23],
       [30, 14, 50,  9, 94],
       [77, 80, 53, 92,  1],
       [72, 27, 42, 89, 66],
       [73, 55, 50, 56, 11]], dtype=int32)

In [40]:
n=np.sum(su,axis=1)
for i in range(len(su)):
    if n[i]>200:
        print(n[i],su[i])

293 [76  8 63 74 72]
278 [94 45 20 31 88]
228 [34 42 13 45 94]
303 [77 80 53 92  1]
296 [72 27 42 89 66]
245 [73 55 50 56 11]


In [3]:
x=np.random.randint(1,101,50)
x

array([ 80,  59,  53,  12,  74, 100,  66,  13,  83,  18,  33,  93,   3,
        29,  90,  67,  96,  45,  93,  99,  46,  75,   1,   3,  43,  91,
        43,  35,  64,  90,  76,  99,  28,  76,  13,  14,  32,   1,  95,
        56,  61,  97,  70,  32,  20,  31,  86,  63,  96,  46], dtype=int32)

In [5]:
m=x.mean()
m

np.float64(55.78)

In [7]:
st=x.std()
st

np.float64(31.39954776744404)

In [9]:
stand= (x - m)/st
stnd = np.round(stand,2)
print(stnd)

[ 0.77  0.1  -0.09 -1.39  0.58  1.41  0.33 -1.36  0.87 -1.2  -0.73  1.19
 -1.68 -0.85  1.09  0.36  1.28 -0.34  1.19  1.38 -0.31  0.61 -1.74 -1.68
 -0.41  1.12 -0.41 -0.66  0.26  1.09  0.64  1.38 -0.88  0.64 -1.36 -1.33
 -0.76 -1.74  1.25  0.01  0.17  1.31  0.45 -0.76 -1.14 -0.79  0.96  0.23
  1.28 -0.31]


In [23]:
#changing negative values into 0 

n=np.array([5, -2, 10, -8, 15, -1])
n[n<0]=0
n

array([ 5,  0, 10,  0, 15,  0])

In [51]:
sales=np.array([250,300,150,400,350,200])
ind=np.argsort(sales)[-3:]
ind

array([1, 4, 3])

In [59]:
#Matrix Column Statistics

col=np.random.randint(1,50,(6,4))
col

array([[37, 17,  8, 27],
       [ 8, 45, 47, 45],
       [22, 12,  6, 13],
       [21,  7, 22, 23],
       [41, 44,  6, 40],
       [36,  1, 49, 15]], dtype=int32)

In [57]:
m=np.mean(col,axis=0)
m


array([25.16666667, 24.33333333, 19.66666667, 34.83333333])

In [58]:
s=np.std(col,axis=0)
s

array([14.24098155, 11.46976702, 12.45882106, 11.03655542])

In [79]:
#data reshaping into matrix
ro=np.random.randint(1,25,24)
ro

array([12, 19,  2, 21,  6, 11, 12,  4,  7, 23, 15, 24, 17,  2,  5, 14,  2,
        6, 17,  3,  9, 23, 18, 13], dtype=int32)

In [80]:
row=np.reshape(ro,(4,6))
row

array([[12, 19,  2, 21,  6, 11],
       [12,  4,  7, 23, 15, 24],
       [17,  2,  5, 14,  2,  6],
       [17,  3,  9, 23, 18, 13]], dtype=int32)

In [69]:
col=np.reshape(ro,(6,4))
col

array([[ 3, 14, 19, 11],
       [23, 15, 20, 18],
       [11,  9, 24, 12],
       [12, 23, 16,  1],
       [12,  3, 16,  1],
       [11, 19,  9,  5]], dtype=int32)

In [74]:
#data extraction

data=np.array([12,45,67,23,89,34,76])
grt= data[data>50]
grt

array([67, 89, 76])

In [75]:
les=data[data<30]
les

array([12, 23])

In [91]:
num=np.random.normal(loc=50,scale=10,size=100)
num
num.mean()

np.float64(48.50483303986047)

In [92]:
num.std()

np.float64(9.145083991966237)