In [8]:
#Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:
import numpy as np
sa=np.random.randint(1000,5001,30)
sa


array([1781, 2563, 1567, 4001, 2350, 2298, 1115, 4521, 4607, 2013, 4222,
       4634, 2631, 1926, 2941, 2746, 4923, 3088, 1957, 1708, 4083, 2805,
       2071, 4250, 1513, 3080, 2266, 4303, 1471, 2063], dtype=int32)

In [2]:
sa.sum()

np.int64(95811)

In [3]:
sa.mean()

np.float64(3193.7)

In [4]:
np.sort(sa)[-5:]

array([4378, 4674, 4832, 4866, 4941], dtype=int32)

In [5]:
!git add .

In [10]:
!git commit -m "numpy practice"

[main c6dce43] numpy practice
 2 files changed, 85 insertions(+), 10 deletions(-)


In [11]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   d4769b3..c6dce43  main -> main


In [18]:
data = np.random.randint(10, 101, 100)


mean = np.mean(data)
std = np.std(data)


z_scores = (data - mean) / std


outliers = data[np.abs(z_scores) > 3]
outliers


array([], dtype=int32)

In [19]:
!git add .

In [20]:
!git commit -m "z score method"

[main 6152422] z score method
 1 file changed, 123 insertions(+), 11 deletions(-)


In [21]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   c6dce43..6152422  main -> main


In [27]:
#normalizing using min-max

a=np.array([120, 150, 200, 250, 300])
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
normalized

array([0.        , 0.16666667, 0.44444444, 0.72222222, 1.        ])

In [28]:
!git add .

In [29]:
!git commit -m "normalization"

[main 6c94de1] normalization
 1 file changed, 73 insertions(+), 18 deletions(-)


In [30]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   6152422..6c94de1  main -> main


In [31]:
age=np.array([18,22,25,30,35,40,45,50,55,60])
age.mean()


np.float64(38.0)

In [35]:
np.median(age)

np.float64(37.5)

In [39]:
age.std()

np.float64(13.66747965061591)

In [40]:
!git add .

In [41]:
!git commit -m "standard deviation"

[main ec7dabc] standard deviation
 1 file changed, 69 insertions(+), 4 deletions(-)


In [42]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   abe5323..ec7dabc  main -> main


In [19]:
su=np.random.randint(1,101,(10,5))
su

array([[24, 66, 32, 38, 18],
       [76,  8, 63, 74, 72],
       [55, 54,  6, 19, 30],
       [94, 45, 20, 31, 88],
       [34, 42, 13, 45, 94],
       [20, 23, 94, 14, 23],
       [30, 14, 50,  9, 94],
       [77, 80, 53, 92,  1],
       [72, 27, 42, 89, 66],
       [73, 55, 50, 56, 11]], dtype=int32)

In [39]:
n=np.sum(su,axis=1)
for i in range(len(su)):
    if n>200:
        print(re[i],su[i])


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()