In [2]:
#Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:
import numpy as np
sa=np.random.randint(1000,5001,30)
sa


array([1952, 3481, 3658, 4023, 1919, 2005, 1514, 2889, 2439, 3560, 1366,
       3387, 4150, 4304, 1818, 4651, 4181, 1266, 4491, 1739, 3601, 2879,
       1459, 1418, 2555, 1393, 3477, 4729, 2602, 3586], dtype=int32)

In [7]:
sa.sum()

np.int64(91556)

In [9]:
sa.mean()

np.float64(3051.866666666667)

In [8]:
np.sort(sa)[-5:]

array([4181, 4304, 4491, 4651, 4729], dtype=int32)

In [9]:
!git add .

In [10]:
!git commit -m "numpy practice"

[main c6dce43] numpy practice
 2 files changed, 85 insertions(+), 10 deletions(-)


In [11]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   d4769b3..c6dce43  main -> main


In [18]:
data = np.random.randint(10, 101, 100)


mean = np.mean(data)
std = np.std(data)


z_scores = (data - mean) / std


outliers = data[np.abs(z_scores) > 3]
outliers


array([], dtype=int32)

In [19]:
!git add .

In [20]:
!git commit -m "z score method"

[main 6152422] z score method
 1 file changed, 123 insertions(+), 11 deletions(-)


In [21]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   c6dce43..6152422  main -> main


In [27]:
#normalizing using min-max

a=np.array([120, 150, 200, 250, 300])
normalized = (a - np.min(a)) / (np.max(a) - np.min(a))
normalized

array([0.        , 0.16666667, 0.44444444, 0.72222222, 1.        ])

In [28]:
!git add .

In [29]:
!git commit -m "normalization"

[main 6c94de1] normalization
 1 file changed, 73 insertions(+), 18 deletions(-)


In [30]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   6152422..6c94de1  main -> main


In [31]:
age=np.array([18,22,25,30,35,40,45,50,55,60])
age.mean()


np.float64(38.0)

In [34]:
me=np.median(age)
me

np.float64(37.5)