In [2]:
#Create a NumPy array of 30 random sales values between 1000 and 5000 and calculate:
import numpy as np
sa=np.random.randint(1000,5001,30)
sa


array([1952, 3481, 3658, 4023, 1919, 2005, 1514, 2889, 2439, 3560, 1366,
       3387, 4150, 4304, 1818, 4651, 4181, 1266, 4491, 1739, 3601, 2879,
       1459, 1418, 2555, 1393, 3477, 4729, 2602, 3586], dtype=int32)

In [7]:
sa.sum()

np.int64(91556)

In [9]:
sa.mean()

np.float64(3051.866666666667)

In [8]:
np.sort(sa)[-5:]

array([4181, 4304, 4491, 4651, 4729], dtype=int32)

In [9]:
!git add .

In [10]:
!git commit -m "numpy practice"

[main c6dce43] numpy practice
 2 files changed, 85 insertions(+), 10 deletions(-)


In [11]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   d4769b3..c6dce43  main -> main


In [14]:
data = np.random.randint(10, 101, 100)


mean = np.mean(data)
std = np.std(data)

# Step 3: calculate Z-scores
z_scores = (data - mean) / std

# Step 4: detect outliers (|z| > 3)
outliers = data[np.abs(z_scores) > 3]


array([29, 41, 24, 25, 45, 19, 87, 49, 16, 59, 95, 74, 81, 80, 14, 59, 52,
       30, 68, 34, 85, 82, 32, 10, 70, 27, 14, 75, 48, 24, 21, 61, 78, 35,
       51, 98, 71, 15, 71, 31, 42, 46, 32, 93, 23, 49, 44, 15, 60, 82, 40,
       36, 23, 90, 92, 37, 64, 12, 60, 54, 76, 71, 17, 50, 98, 26, 19, 42,
       48, 85, 97, 25, 44, 17, 23, 19, 30, 76, 35, 41, 94, 82, 90, 17, 64,
       48, 92, 17, 57, 91, 27, 54, 73, 81, 79, 11, 40, 71, 44, 51],
      dtype=int32)

array([], dtype=int32)