In [1]:
l1=[2,5,6,7,8,3,1]
l1

[2, 5, 6, 7, 8, 3, 1]

In [3]:
l_new=[]
for i in l1:
    l_new.append(i+2)
l_new    

[4, 7, 8, 9, 10, 5, 3]

In [2]:
import numpy as np
a1=np.array([2,5,6,7,8,3,1])
a1

array([2, 5, 6, 7, 8, 3, 1])

In [5]:
a1+2

array([ 4,  7,  8,  9, 10,  5,  3])

In [6]:
a2=np.array([2,3,23.5,True,"akash"])
a2

array(['2', '3', '23.5', 'True', 'akash'], dtype='<U32')

In [7]:
#converts all the data into float value
#heterogenous to homogenous
a2=np.array([2,3,23.5,True])

In [8]:
a2

array([ 2. ,  3. , 23.5,  1. ])

In [10]:
a3=np.array([[1,2,3,4],[5,6,7,8]])
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
#gives both number of rows and columns
a3.shape

(2, 4)

In [17]:
#rows
a3.shape[0]

2

In [18]:
#columns
a3.shape[1]

4

In [19]:
#dimension of array
a3.ndim

2

In [20]:
a3.dtype

dtype('int64')

In [21]:
#total numbers of elements in array
a3.size

8

In [22]:
tl= list(a3)
tl


[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [25]:
ta=np.array(tl)
ta

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
x=np.array([[2,4],[3,5]])
x

array([[2, 4],
       [3, 5]])

In [28]:
y=np.array([[1,6],[7,4]])
y

array([[1, 6],
       [7, 4]])

In [32]:
x+y


array([[ 3, 10],
       [10,  9]])

In [30]:
x-y

array([[ 1, -2],
       [-4,  1]])

In [31]:
x/y

array([[2.        , 0.66666667],
       [0.42857143, 1.25      ]])

In [33]:
x*y

array([[ 2, 24],
       [21, 20]])

In [34]:
 np.matmul(x,y)

array([[30, 28],
       [38, 38]])

In [35]:
 !git add .

In [36]:
!git commit -m "new new file named as numpy"

[main 6bab973] new new file named as numpy
 3 files changed, 939 insertions(+), 3 deletions(-)
 create mode 100644 .ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 Untitled.ipynb


In [37]:
!git push

To https://github.com/CodeWithAkash/python-class-notes.git
   86e0b40..6bab973  main -> main


In [3]:
d1= np.array([[2,8,9,5],[1,4,6,0],[3,2,7,1]])
d1

array([[2, 8, 9, 5],
       [1, 4, 6, 0],
       [3, 2, 7, 1]])

In [4]:
d1[1,2]

np.int64(6)